from Genetic.ReplacementMethods.BaseReplacement import BaseReplacement
from Genetic.ReplacementMethods.SelectiveReplacement import SelectiveReplacement
from Genetic.ReplacementMethods.ReplaceWorst import ReplaceWorst