from Genetic.PopulationUpdaters.PopulationUpdaters import PopulationUpdaters
from Genetic.PopulationUpdaters.SimpleSwapper import SimpleSwapper
from Genetic.PopulationUpdaters.BestsIndividuals import BestsIndividuals
from Genetic.PopulationUpdaters.HybridElitism import HybridElitism