from Genetic.PopulationGenerators.PopulationGenerator import PopulationGenerator
from Genetic.PopulationGenerators.ApproximatedSize import ApproximatedSize
from Genetic.PopulationGenerators.FixedSize import FixedSize